/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArraysIndexRouteImport } from './routes/arrays/index'
import { Route as ProblemsIdRouteImport } from './routes/problems/$id'
import { Route as ArraysTestRouteImport } from './routes/arrays/test'
import { Route as Arrays217RouteImport } from './routes/arrays/217'

const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArraysIndexRoute = ArraysIndexRouteImport.update({
  id: '/arrays/',
  path: '/arrays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArraysTestRoute = ArraysTestRouteImport.update({
  id: '/arrays/test',
  path: '/arrays/test',
  getParentRoute: () => rootRouteImport,
} as any)
const Arrays217Route = Arrays217RouteImport.update({
  id: '/arrays/217',
  path: '/arrays/217',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/arrays/217': typeof Arrays217Route
  '/arrays/test': typeof ArraysTestRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/arrays': typeof ArraysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/arrays/217': typeof Arrays217Route
  '/arrays/test': typeof ArraysTestRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/arrays': typeof ArraysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/arrays/217': typeof Arrays217Route
  '/arrays/test': typeof ArraysTestRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/arrays/': typeof ArraysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/arrays/217'
    | '/arrays/test'
    | '/problems/$id'
    | '/arrays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice'
    | '/arrays/217'
    | '/arrays/test'
    | '/problems/$id'
    | '/arrays'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/arrays/217'
    | '/arrays/test'
    | '/problems/$id'
    | '/arrays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  Arrays217Route: typeof Arrays217Route
  ArraysTestRoute: typeof ArraysTestRoute
  ProblemsIdRoute: typeof ProblemsIdRoute
  ArraysIndexRoute: typeof ArraysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrays/': {
      id: '/arrays/'
      path: '/arrays'
      fullPath: '/arrays'
      preLoaderRoute: typeof ArraysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrays/test': {
      id: '/arrays/test'
      path: '/arrays/test'
      fullPath: '/arrays/test'
      preLoaderRoute: typeof ArraysTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrays/217': {
      id: '/arrays/217'
      path: '/arrays/217'
      fullPath: '/arrays/217'
      preLoaderRoute: typeof Arrays217RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  Arrays217Route: Arrays217Route,
  ArraysTestRoute: ArraysTestRoute,
  ProblemsIdRoute: ProblemsIdRoute,
  ArraysIndexRoute: ArraysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
